grpc:
  server:
    address: 127.0.0.1
    port: 9900

spring:
  application:
    name: education-tag-service
  main:
    web-application-type: NONE
  datasource:
    url: jdbc:postgresql://localhost:5432/education_utility_service
    driver-class-name: org.postgresql.Driver
    username: education
    password: education
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none